base-url: /
destination: ./_site
#server: true
#auto: true
lsi: true
server_port: 5001
pygments: true
markdown: redcloth
permalink: 	/archives/:year/:month/:day/:title/
paginate: 10
plugins: ./_plugins
main_domain: blogsoso.com

